---
name: publish
on:
  push:
    branches:
      - source

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
        with:
          submodules: true

      - name: install python virtualenv
        run: |
          sudo apt update
          sudo apt install -y python-virtualenv

      - name: install requirements
        run: |
          virtualenv .venv
          source .venv/bin/activate

          pip install -r requirements.txt

          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          make github

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
